package models

//TokenType ...
type TokenType string

const (
	//FLOTANTE ...
	FLOTANTE TokenType = "FLOTANTE"
	//ENTERO ...
	ENTERO = "ENTERO"
	//CADENA ...
	CADENA = "CADENA"
	//ALFABETICO ...
	ALFABETICO = "ALFABETICO"
	//LOGICO ...
	LOGICO = "LOGICO"
	//REAL ...
	REAL = "REAL"
)
